platform :ios, '9.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :path => '../'

target 'ChatExampleTests' do
  inherit! :search_paths
end

target 'ChatExampleUITests' do
  inherit! :search_paths
end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      config.build_settings['SWIFT_VERSION'] = '4.2'
    end
  end
end
